from pathlib import Path

path = Path('scanner/stream.py')
backup = path.with_suffix('.py.before_dynamic_sl_display')
backup.write_text(path.read_text())
s = path.read_text()

old_event = '''        if event:\n            print()\n            print("=" * 82)\n\n            if event["event"] == "TARGET_1_HIT":\n                self.session_stats["target1"] += 1\n                print("🏆🏆 TARGET 1 HIT")\n                print(f"💰 Profit Booked : ₹{event['pnl']:,.2f}")\n\n            elif event["event"] == "TARGET_2_HIT":\n                self.session_stats["target2"] += 1\n                print("🥈🥈 TARGET 2 HIT")\n                print(f"💰 Profit Booked : ₹{event['pnl']:,.2f}")\n\n            elif event["event"] == "TARGET_3_HIT":\n                self.session_stats["target3"] += 1\n                self.session_stats["wins"] += 1\n                self.session_stats["gross_profit"] += event["pnl"]\n                self.session_stats["active"] -= 1\n                print("👑👑👑 TARGET 3 ACHIEVED")\n                print(f"💰 Final Profit : ₹{event['pnl']:,.2f}")\n                print()\n                print("🟢🟢✅✅ TRADE CLOSED (PROFIT)")\n                print()\n\n            elif event["event"] == "STOP_LOSS_HIT":\n                self.session_stats["stoploss"] += 1\n                self.session_stats["losses"] += 1\n                self.session_stats["gross_loss"] += abs(event["pnl"])\n                self.session_stats["active"] -= 1\n                print("😭😭 STOP LOSS HIT")\n                print(f"💸 Loss Booked : ₹{abs(event['pnl']):,.2f}")\n                print()\n                print("🔴🔴❌❌ TRADE CLOSED (LOSS)")\n                print()\n\n            print()\n            print(f"🔢 Trade No. : {event['trade_number']}")\n            print(f"📊 Stock     : {event['display_symbol']}")\n            if event["event"] in ("TARGET_3_HIT", "STOP_LOSS_HIT"):\n                print(f"🏁 Exit      : {event['exit_reason']}")\n                print(f"⏱ Duration  : {event['duration']}")\n            print(f"🕒 Time      : {datetime.now().strftime('%H:%M:%S')}")\n            print("=" * 82)\n            print()\n\n'''

new_event = '''        if event:
            active_after_event = get_active_trades().get(event["symbol"])
            protected_profit = 0.0
            if active_after_event and active_after_event.get("target2_hit"):
                protected_profit = active_after_event["risk"]["recommended_qty"] * abs(
                    active_after_event["target1"] - active_after_event["entry"]
                )\n            print()\n            print("=" * 82)\n\n            if event["event"] == "TARGET_1_HIT":\n                self.session_stats["target1"] += 1\n                print("🏆🏆 TARGET 1 ACHIEVED")\n                print(f"💰 Profit Level       : ₹{event['pnl']:,.2f}")\n                print("🛡️ STOP LOSS MOVED    : ENTRY")\n                print("🔒 Protected Minimum  : ₹0.00")\n                print("🎯 Next Target        : TARGET 2")\n\n            elif event["event"] == "TARGET_2_HIT":\n                self.session_stats["target2"] += 1\n                print("🥈🥈 TARGET 2 ACHIEVED")\n                print(f"💰 Profit Level       : ₹{event['pnl']:,.2f}")\n                print("🛡️ STOP LOSS MOVED    : TARGET 1")\n                print(f"🔒 Protected Minimum  : ₹{protected_profit:,.2f}")\n                print("🎯 Next Target        : TARGET 3")\n\n            elif event["event"] == "TARGET_3_HIT":\n                self.session_stats["target3"] += 1\n                self.session_stats["wins"] += 1\n                self.session_stats["gross_profit"] += event["pnl"]\n                self.session_stats["active"] -= 1\n                print("👑👑👑 TARGET 3 ACHIEVED")\n                print(f"💰 Final Profit        : ₹{event['pnl']:,.2f}")\n                print()\n                print("🟢🟢✅✅ TRADE CLOSED (PROFIT)")\n                print()\n\n            elif event["event"] == "STOP_LOSS_HIT":\n                self.session_stats["stoploss"] += 1\n                self.session_stats["losses"] += 1\n                self.session_stats["gross_loss"] += abs(event["pnl"])\n                self.session_stats["active"] -= 1\n                print("😭😭 STOP LOSS HIT")\n                print(f"💸 Loss Booked        : ₹{abs(event['pnl']):,.2f}")\n                print()\n                print("🔴🔴❌❌ TRADE CLOSED (LOSS)")\n                print()\n\n            print()\n            print(f"🔢 Trade No. : {event['trade_number']}")\n            print(f"📊 Stock     : {event['display_symbol']}")\n            if event["event"] in ("TARGET_3_HIT", "STOP_LOSS_HIT"):\n                print(f"🏁 Exit      : {event['exit_reason']}")\n                print(f"⏱ Duration  : {event['duration']}")\n            print(f"🕒 Time      : {datetime.now().strftime('%H:%M:%S')}")\n            print("=" * 82)\n            print()\n\n'''

if s.count(old_event) != 1:
    raise SystemExit(f'ERROR: expected exactly 1 event banner block, found {s.count(old_event)}. NO CHANGES MADE.')

s = s.replace(old_event, new_event)

old_active = '''        if active:\n            print("🟢 ACTIVE POSITIONS")\n            for trade in sorted(active.values(), key=lambda x: x["trade_number"]):\n                duration = datetime.now() - trade["opened_at"]\n                mins = int(duration.total_seconds() // 60)\n                secs = int(duration.total_seconds() % 60)\n\n                print(\n                    f"#{trade['trade_number']:02d} "\n                    f"{trade['action']:<4} "\n                    f"{trade['display_symbol']:<15} "\n                    f"⏱ {mins:02d}m {secs:02d}s"\n                )\n\n            print()\n'''

new_active = '''        if active:\n            print("🟢 ACTIVE POSITIONS / DYNAMIC SL")\n            protected_total = 0.0\n            t1_protected = 0\n            t2_protected = 0\n\n            for trade in sorted(active.values(), key=lambda x: x["trade_number"]):\n                duration = datetime.now() - trade["opened_at"]\n                mins = int(duration.total_seconds() // 60)\n                secs = int(duration.total_seconds() % 60)\n\n                risk = trade["risk"]\n                qty = risk["recommended_qty"]\n                entry = trade["entry"]\n                target1 = trade["target1"]\n                stop_loss = trade["stop_loss"]\n\n                if trade["target2_hit"]:\n                    sl_state = "TARGET 1"\n                    protected = qty * abs(target1 - entry)\n                    t2_protected += 1\n                elif trade["target1_hit"]:\n                    sl_state = "ENTRY"\n                    protected = 0.0\n                    t1_protected += 1\n                else:\n                    sl_state = "ORIGINAL"\n                    protected = 0.0\n\n                protected_total += protected\n\n                print(\n                    f"#{trade['trade_number']:02d} "\n                    f"{trade['action']:<4} "\n                    f"{trade['display_symbol']:<15} "\n                    f"SL → {sl_state:<8} "\n                    f"₹{stop_loss:,.2f} "\n                    f"⏱ {mins:02d}m {secs:02d}s"\n                )\n\n            print()\n            print("🛡️ DYNAMIC STOP LOSS STATUS")\n            print(f"🏆 T1 reached / SL → ENTRY    : {t1_protected}")\n            print(f"🥈 T2 reached / SL → TARGET 1 : {t2_protected}")\n            print(f"🔒 Protected Minimum Profit    : ₹{protected_total:,.2f}")\n            print()\n'''

if s.count(old_active) != 1:
    raise SystemExit(f'ERROR: expected exactly 1 active summary block, found {s.count(old_active)}. NO CHANGES MADE.')

s = s.replace(old_active, new_active)
path.write_text(s)
print('DISPLAY PATCH APPLIED')
